# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc282df8a6b03906314844d5a6eff48f82239a458e5d3887974903bffbc677b2c0eb7895b283ddbaabd99b716f779b6d8382b7545fb19360c9c502209c232931

test:
  secret_key_base: aee19356a5cddefb2c3639e7d3dda24106ac4d2457e7969379b3baa9e5cffa7bc1e2eb15a98733e505d5157fe76b8402b93a1a229c85442cd7062e41cb29688f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
